[tool.ruff]
line-length = 120
preview = true
target-version = "py313"
lint.select = ["ALL"]
lint.ignore = [
    "COM812", "ISC001",  # These rules may cause conflicts when used with the ruff formatter

    "C90",
    "S",
    "BLE",
    "FBT",
    "A",
    "CPY",
    "PT",  # pytest
    "SLF",
    "FIX",
    "ERA",  # commented out code
    "ARG",  # gives too many Unused method argument, we should clean them up later


    "E501",
    "N801", "N802", "N803", "N805", "N806", "N818",
    "B005", "B905", "B017", "B027", "B019",
    "DJ008", "DJ012", "DJ001",
    "PD013",  # Use melt() instead of stack()
    "PD011",  # Use `.to_numpy()` instead of `.values`
    "PD901",  # df is a bad variable name
    "PLR0904",  # Too many public methods
    "PLR0913",  # Too many arguments to function call
    "PLR0915",  # Too many statements
    "PLR0912",  # Too many branches
    "PLR0911",  # Too many return statements
    "PLR0914",  # Too many local variables
    "PLR0917",  # Too many positional arguments
    "PLR1702",  # Too many nested blocks
    "PLR2004",  # Magic value used in comparison
    "PLR6301",  # Method `perform_update` could be a function or static method
    "PLW2901",  # `for` loop variable ... overwritten by assignment target
    "RUF001",  # Doesn't work well with French words, like d'authentication
    "RUF012",  # Too many issues with DRF classes and Django
    # Missing annotations
    "ANN001", "ANN002", "ANN003", "ANN201", "ANN202", "ANN204", "ANN205", "ANN206",
    "TRY301",  # false positives
    "DTZ001", "DTZ002", "DTZ005", "DTZ011",  # should fix time zone issues gradually

    "D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107",
    "D203", "D212",  # D203 and D211, D212 and D213 are mutually exclusive
    "D205", "D401", "D404",
    "DOC201",  # `return` is not documented in docstring
    "DOC402",  # `yield` is not documented in docstring
    "DOC501",  # Raised exception ... missing from docstring"

    "PLC1901",  # too much legacy (empty string is falsey)
    "PLC0415",  # we have many imports inside functions to avoid circular import errors
    "PLR0916",  # we disable complexity checks (Too many Boolean expressions)

    # temporary exceptions
    "DTZ",
]
